Shop 29 section banner
RealSpiffy/shop pull request #14
Opened 2023-03-17 20:50 UTC by sprajams

- create section banner component
- optional subtitle and action (currently a placeholder) fields

2023-03-19 01:02 UTC, scottqmn requested changes
Looks good! just one comment

2023-03-19 01:02 UTC, scottqmn commented on src/components/SectionBanner/SectionBanner.tsx
> +      <h2 className={clsx(styles.main, styles.wordBreak)}>{heading}</h2>
Remove h2 and h4 headings

2023-03-21 18:00 UTC, sprajams commented on src/components/SectionBanner/SectionBanner.tsx
> +      <h2 className={clsx(styles.main, styles.wordBreak)}>{heading}</h2>
Add dynamic tags in place of removing heading tags completely

2023-03-23 14:52 UTC, scottqmn requested changes
Same comments as #28 regarding dynamic tags

2023-04-07 03:33 UTC, scottqmn approved these changes

2023-04-07 18:46 UTC, merged