SHOP-6-Collection-Link-Component
RealSpiffy/shop pull request #2
Opened 2023-01-13 17:59 UTC by sprajams

- Add simple collection link component
- Configuration for storybook

2023-01-15 19:06 UTC, scottqmn requested changes
Looks good just left some comments with room for cleanup

2023-01-15 19:06 UTC, scottqmn commented on src/components/CollectionLink/CollectionLink.tsx
> +    <>
Remove fragments. Should be:
```
return href ?
 <Link ...>
: <div ...>

2023-01-15 19:06 UTC, scottqmn commented on src/components/CollectionLink/CollectionLink.tsx
> +  //main content
Remove comments unless describing function utility

2023-01-15 19:06 UTC, scottqmn commented on src/components/CollectionLink/CollectionLink.tsx
> +          <span className={styles.linkArrow}>{`>`}</span>
Use corresponding MUI icon

2023-01-15 19:06 UTC, scottqmn commented on src/components/CollectionLink/CollectionLink.tsx
> +          {/* disabled warning to use next/image just for this file... */}
```
{/* eslint-disable-next-line @next/next/no-img-element */}

2023-01-15 19:06 UTC, scottqmn commented on src/components/CollectionLink/styles.module.scss
> +  box-shadow: 0 4px 4px rgba(0, 0, 0, 0.25);
Remove box-shadow

2023-01-15 19:06 UTC, scottqmn commented on src/components/CollectionLink/styles.module.scss
> +  &.overlay {
Handle overlay in its own element adjacent to bg <img>

2023-01-15 19:06 UTC, scottqmn commented on src/components/CollectionLink/styles.module.scss
> +  display: flex;
Remove flex, handle chevron positioning with `position: absolute`, set to `display: block` to reset <a> styles

2023-01-15 19:06 UTC, scottqmn commented on src/components/CollectionLink/styles.module.scss
> +  &.link {
Could just leave this styling in the original class

2023-01-15 19:06 UTC, scottqmn commented on src/components/CollectionLink/styles.module.scss
> +  z-index: -1;
Rm

2023-01-15 19:06 UTC, scottqmn commented on src/components/CollectionLink/styles.module.scss
> +  margin-left: auto;
Handle with positioning

2023-01-15 19:06 UTC, scottqmn commented on src/components/CollectionLink/CollectionLink.stories.tsx
> +  background: {
Good usage of placeholder data but can be optimized:
```
const placeholderBg = {
  src: "https://picsum.photos/id/14/200/200",
  alt: "collection 1",
}

... 

Default.args = {
  background: placeholderBg
}

...

NoHref.args = {
  background: placeholderBg
}

2023-01-16 20:01 UTC, sprajams commented on src/components/CollectionLink/CollectionLink.tsx
> +          <span className={styles.linkArrow}>{`>`}</span>
used react-icons instead

2023-01-16 23:18 UTC, scottqmn approved these changes

2023-01-16 23:21 UTC, merged